### ISSUE TITLE
Additional UI components

### ISSUE THREAD

**Issue by andrii-trush** [gilbitron/laravel-vue-pagination#10]
Hello. Thank you for great plugin. But I need some additional functions:

1. ![Image of Yaktocat](https://raw.githubusercontent.com/lokyoung/vuejs-paginate/master/img/pagination-show.gif)
2. Customize Prev and Next buttons. Would like to change custom buttons

**Comment by andrii-trush** [comment]
@gilbitron Thanks. And what about second issue?

**Comment by gilbitron** [comment]
I've left this ticket open for the next time I get time to work on 2 (or someone else could submit a PR 😉).

**Comment by gilbitron** [comment]
Customizing Prev and Next buttons is now available in [v1.2.0](https://github.com/gilbitron/laravel-vue-pagination/releases/tag/1.2.0)
