### ISSUE TITLE
How to use this package in Vue 3 ?

### ISSUE THREAD

**Issue by joneyspark** [gilbitron/laravel-vue-pagination#100]
Hi, I am trying to use this pagination package for Vue 3 and Laravel 7 but I got an error 

http://prntscr.com/10xwf27

main.js

```
let app = createApp(App);
app.component('pagination', require('laravel-vue-pagination'));
app.mount("#app");
```

**Is it support Vue 3 ???**

**Comment by gilbitron** [comment]
I'm afraid this package doesn't support Vue 3 yet.

**Comment by joneyspark** [comment]
I am using another package 

https://www.npmjs.com/package/v-pagination-3

Hope you will upgrade the package and people can use the package for Vue 3

Thanks

**Comment by saadabdurrazaq** [comment]
Same here, I got an error like what @joneyspark mentioned above. Can you fix the error @gilbitron ?

**Comment by joneyspark** [comment]
@gilbitron If you are using Vue 3 the vue-pagination not working. You can use the below package

https://www.npmjs.com/package/v-pagination-3

**Comment by saadabdurrazaq** [comment]
@joneyspark I am now using that package. But I am not able to show a value dynamically for `:records` and `:per-page`. I didnt found any tutorial about it.

**Comment by joneyspark** [comment]
@saadabdurrazaq you have to get the total data length for :records and for :per-page you have to set value the paginate number

**Comment by saadabdurrazaq** [comment]
It's done. Yes, I did. It's work. But there is another problem, I still find out to place pagination bar in the right bottom.

**Comment by saadabdurrazaq** [comment]
Hi @joneyspark can you please help me how place this element in the right side? I use the package ( https://www.npmjs.com/package/v-pagination-3) as you recommend to me. 
![pag](https://user-images.githubusercontent.com/15057404/122898984-95a22d00-d375-11eb-9cfb-0d0574e7a252.png)

**Comment by gilbitron** [comment]
@saadabdurrazaq Can I ask that you please keep the conversation in this issue related to the `laravel-vue-pagination` package. You can ask questions about the `v-pagination-3` [over here](https://github.com/matfish2/vue-pagination-2/tree/vue3).

**Comment by bhojkamal** [comment]
Hope this package support for Vue 3 js soon.

**Comment by gilbitron** [comment]
https://github.com/gilbitron/laravel-vue-pagination/releases/tag/3.0.0
