### ISSUE TITLE
How to configure for Nuxt js?

### ISSUE THREAD

**Issue by zarpio** [gilbitron/laravel-vue-pagination#109]
1) installed via
`npm i laravel-vue-pagination`

2) created a file under plugins folder as "laravel-vue-pagination.js"
```
import Vue from 'vue'
import LaravelVuePagination from 'laravel-vue-pagination'

Vue.use('laravel-vue-pagination', LaravelVuePagination)
```
3) registered in nuxt.config.js under plugins array
`'~/plugins/laravel-vue-pagination'
`
4) using in page as follows
`<LaravelVuePagination :data="users" @pagination-change-page="getResults"></LaravelVuePagination>`

5) Getting error
**Cannot create property '__nuxt_external_installed__' on string 'laravel-vue-pagination'**

**Comment by anburocky3** [comment]
@zarpio Have you found any solution regarding this?

**Comment by zarpio** [comment]
> @zarpio Have you found any solution regarding this?

Yes, in `plugins/laravel-vue-pagination.js` as follows.

```
import Vue from 'vue'
import LaravelVuePagination from 'laravel-vue-pagination'
Vue.component('laravel-vue-pagination', LaravelVuePagination)
```

**Comment by anburocky3** [comment]
Do you have any open source project to view this?
