### ISSUE TITLE
Page number limits will be doubled to the assigined number

### ISSUE THREAD

**Issue by renwarkurd** [gilbitron/laravel-vue-pagination#111]
Hi,
The page number limits when assigned to a number like 10, it will be 20 when clicking on subsequent numbers resulted in change in wrapper width which is annoying to user.

**Comment by gilbitron** [comment]
That's correct. From the description of the `limit` field:

> Any positive integer (e.g. 2) will define how many pages should be shown on **_either side_** of the current page when only a range of pages are shown.
