### ISSUE TITLE
43 Warning while importing the package 

### ISSUE THREAD

**Issue by ziyadadel** [gilbitron/laravel-vue-pagination#129]
*the result of npm watch*

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 206:35-53
export 'createElementVNode' (imported as 'createElementVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 207:35-53
export 'createElementVNode' (imported as 'createElementVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 213:35-53
export 'createElementVNode' (imported as 'createElementVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 214:35-53
export 'createElementVNode' (imported as 'createElementVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 216:52-68
export 'resolveComponent' (imported as 'resolveComponent') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 217:9-18
export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 217:22-33
export 'createBlock' (imported as 'createBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 225:13-20
export 'withCtx' (imported as 'withCtx') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 226:63-72
export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 226:76-94
export 'createElementBlock' (imported as 'createElementBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 226:101-111
export 'mergeProps' (imported as 'mergeProps') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 234:68-77
export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 234:81-99
export 'createElementBlock' (imported as 'createElementBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 236:17-31
export 'normalizeClass' (imported as 'normalizeClass') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 238:10-28
export 'createElementVNode' (imported as 'createElementVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 238:34-44
export 'mergeProps' (imported as 'mergeProps') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 243:13-23
export 'toHandlers' (imported as 'toHandlers') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 244:12-22
export 'renderSlot' (imported as 'renderSlot') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 249:17-35
export 'createCommentVNode' (imported as 'createCommentVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 250:9-18
export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 250:26-44
export 'createElementBlock' (imported as 'createElementBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 250:45-53
export 'Fragment' (imported as 'Fragment') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 250:61-71
export 'renderList' (imported as 'renderList') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 251:17-26
export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 251:30-48
export 'createElementBlock' (imported as 'createElementBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 252:19-33
export 'normalizeClass' (imported as 'normalizeClass') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 255:12-30
export 'createElementVNode' (imported as 'createElementVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 255:36-46
export 'mergeProps' (imported as 'mergeProps') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 258:15-25
export 'toHandlers' (imported as 'toHandlers') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 259:14-29
export 'createTextVNode' (imported as 'createTextVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 259:30-45
export 'toDisplayString' (imported as 'toDisplayString') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 260:56-65
export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 260:69-87
export 'createElementBlock' (imported as 'createElementBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 260:124-142
export 'createCommentVNode' (imported as 'createCommentVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 264:68-77
export 'openBlock' (imported as 'openBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 264:81-99
export 'createElementBlock' (imported as 'createElementBlock') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 266:17-31
export 'normalizeClass' (imported as 'normalizeClass') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 268:10-28
export 'createElementVNode' (imported as 'createElementVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 268:34-44
export 'mergeProps' (imported as 'mergeProps') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 273:13-23
export 'toHandlers' (imported as 'toHandlers') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 274:12-22
export 'renderSlot' (imported as 'renderSlot') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 279:17-35
export 'createCommentVNode' (imported as 'createCommentVNode') was not found in 'vue' (possible exports: default)

WARNING in ./node_modules/laravel-vue-pagination/dist/laravel-vue-pagination.es.js 280:16-34
export 'createCommentVNode' (imported as 'createCommentVNode') was not found in 'vue' (possible exports: default)

webpack compiled with 43 warnings

**Comment by Lordin** [comment]
Same problem here.

**Comment by reckoan** [comment]
Same problem here also

**Comment by lazic12** [comment]
Hey guys, you're probably using version 3.0.0 with vue": "^2.6.14, 
just try using lower version
npm install laravel-vue-pagination@2.3.1
that worked for me

**Comment by felloz** [comment]
> Hey guys, you're probably using version 3.0.0 with vue": "^2.6.14, just try using lower version npm install laravel-vue-pagination@2.3.1 that worked for me

What vue version should i use with LVP@3.0.0?

**Comment by gilbitron** [comment]
[Laravel Vue Pagination v3](https://github.com/gilbitron/laravel-vue-pagination/releases/tag/3.0.0) is only compatible with Vue 3. If you are using Vue 2 please use [Laravel Vue Pagination v2](https://github.com/gilbitron/laravel-vue-pagination/releases/tag/2.3.2). However, please note that v2 is no longer actively maintained.
