### ISSUE TITLE
app.js:109006 Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by felloz** [gilbitron/laravel-vue-pagination#136]
**Describe the bug**
1. I installed the library, then imported in my app.js as you explain in the documentation.
2. I ran npm run watch and compiled succesful
3. I refresh the url in the webroser
4.Got the next error:

![image](https://user-images.githubusercontent.com/26178285/175754993-703512f8-2de6-4cab-bfaa-992996c5d75d.png)

**Version information (please complete the following information):**
 - laravel-vue-pagination: 3.0.0
 - Vue: ^2.6.12
 - Laravel: 8.6.0

**Comment by MATOVUJOELCLINTON** [comment]
i got the same error after installing it in 
- Laravel ^7.29 and Vue ^2.5.17

it seems you can't use it as a Global component in app.js file

**Comment by gilbitron** [comment]
[Laravel Vue Pagination v3](https://github.com/gilbitron/laravel-vue-pagination/releases/tag/3.0.0) is only compatible with Vue 3. If you are using Vue 2 please use [Laravel Vue Pagination v2](https://github.com/gilbitron/laravel-vue-pagination/releases/tag/2.3.2). However, please note that v2 is no longer actively maintained.
