### ISSUE TITLE
Boostrap 4 centered pagination

### ISSUE THREAD

**Issue by G3z** [gilbitron/laravel-vue-pagination#15]
in bootstap 4 pagination is controlled with a specific class
https://getbootstrap.com/docs/4.0/components/pagination/#alignment
is it possible to implement an `alignment` prop  ?

**Comment by gilbitron** [comment]
I'll consider adding it.

In the meantime, I think it's probably fine to target the `pagination` class and use the [`justify-content` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content).

**Comment by gilbitron** [comment]
I've decided not to add this unless more people ask for it. Using external CSS is a reasonable workaround.

**Comment by ultrono** [comment]
For Bootstrap 4 you could just add the following in your Vue component:

`<style scoped>
    .pagination {
        justify-content: center!important;
    }
</style>`

**Comment by mehmetkutuks** [comment]
> For Bootstrap 4 you could just add the following in your Vue component:
> 
> `<style scoped> .pagination { justify-content: center!important; } </style>`

thanks :)
