### ISSUE TITLE
Custom page name doesn't work

### ISSUE THREAD

**Issue by Qoraiche** [gilbitron/laravel-vue-pagination#185]
**Describe the bug**
It keeps using the default ?page, even if i put a custom page name:

 `$buyers->paginate(3, [*], 'custompagename')`

**To Reproduce**
Add a custom page name to ->paginate() builder and try to navigate pagination front, it still adds a ?page to the url instead of **?custompagename**

**Expected behavior**
?custompagename should be used instead

**Version information**
 - laravel-vue-pagination": "^4.1.1"
-  Vue : "^3.2.31",
 - Laravel: 10.*

**Comment by gilbitron** [comment]
This library is not responsible for how you fetch your data. You would need to update your fetch URL query string to use `custompagename` instead. See [the docs](https://laravel-vue-pagination.org/guide/quick-start.html) for an example.
