### ISSUE TITLE
Support Laravel API Resources

### ISSUE THREAD

**Issue by gilbitron** [gilbitron/laravel-vue-pagination#22]
This should be able to support the different format used by Laravel's API resources: https://laravel.com/docs/5.6/eloquent-resources#pagination

```
{
    "data": [
        {
            "id": 1,
            "name": "Eladio Schroeder Sr.",
            "email": "therese28@example.com",
        },
        {
            "id": 2,
            "name": "Liliana Mayert",
            "email": "evandervort@example.com",
        }
    ],
    "links":{
        "first": "http://example.com/pagination?page=1",
        "last": "http://example.com/pagination?page=1",
        "prev": null,
        "next": null
    },
    "meta":{
        "current_page": 1,
        "from": 1,
        "last_page": 1,
        "path": "http://example.com/pagination",
        "per_page": 15,
        "to": 10,
        "total": 10
    }
}
```

**Comment by Galironfydar** [comment]
A quick solution was to pass `:data="example.meta"` in the pagination prop. But, I would love to see better support for this 👍

**Comment by reado** [comment]
To elaborate on @Galironfydar's response.. My collection has a lot of items and I also wanted to incorporate the First & Last links as well.  I guess when returning a collection, the key for `next` and `prev` have also changed since they're lumped within the `links` object.

I created a computed property that combined and modified the Resource Collection response so that this component can use those URLs as well.  Ideally this plugin would have better support for resources but this is currently working
```
<pagination :data="linkdata" @pagination-change-page="populateImages"></pagination>
```

```
  data() {
	return {
		images: {},
	}
  },
  mounted() {
	this.populateImages();
  },
  computed: {
        linkdata() {
            if (this.images.links) {
                Object.defineProperty(this.images.links, 'next_page_url', Object.getOwnPropertyDescriptor(this.images.links, 'next'));
                delete this.images.links['next'];

                Object.defineProperty(this.images.links, 'prev_page_url', Object.getOwnPropertyDescriptor(this.images.links, 'prev'));
                delete this.images.links['prev'];
            }

           const linkData = {
                ...this.images.meta,
                ...this.images.links,
            };
            return linkData;
        }
},

```

**Comment by ultrono** [comment]
Prev and next links do not appear when using api resources :/

**Comment by gilbitron** [comment]
This has been added in [v2.1.0](https://github.com/gilbitron/laravel-vue-pagination/releases/tag/2.0.1)
