### ISSUE TITLE
Implement renderless component

### ISSUE THREAD

**Issue by gilbitron** [gilbitron/laravel-vue-pagination#23]
I think it would make sense to implement this as a [renderless component](https://adamwathan.me/renderless-components-in-vuejs/) and provide default template components for Bootstrap 3/4.

https://learn.adamwathan.com/advanced-vue/getting-started-with-renderless-ui-components

**Comment by gilbitron** [comment]
Done in https://github.com/gilbitron/laravel-vue-pagination/releases/tag/2.0.0

**Comment by YutaInoueCommudePH** [comment]
@gilbitron 
Hello, may I know how customize the layout from the renderless component? 
Is there a prop that can point to my custom template.
