### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by robertnicjoo** [gilbitron/laravel-vue-pagination#26]
Hi,
I just installed this and I think I did everything in documentation but somehow it won't work,

`controller`

```php
$projects = Project::orderby('id', 'desc')->paginate(10);
```

`vue template`

```html
<pagination :data="projects" @pagination-change-page="load"></pagination>
```

`component script`

```js
import pagination from 'laravel-vue-pagination';  //added here
    export default {
        data() {
            return {
                projects: []
            }
        },
        mounted: function() {
            if (this.projects.length) {
                return;
            }
            this.load()
        },
        methods: {
            load: function(page) { //added here
                if (typeof page === 'undefined') {
                    page = 1 //added here
                }
                axios.get('/api/projects?page=' + page) //added here
                .then(
                    response => {
                        this.projects =  (response.data);
                    }     
                )
                .catch(function (error) {
                    this.errors.push(error);
                    console.log(error);
                })
            }
        }
    }
```

# Question

Did I do something wrong? How to fix this?

**Comment by gilbitron** [comment]
Your code looks ok. In what way does it not work? Are there any errors in the console?

**Comment by robertnicjoo** [comment]
@gilbitron  hi, thanks for response,
since I published this issue i've changed my script a bit (new one below)

```javascript
<script>
import pagination from 'laravel-vue-pagination';

    export default {
        data() {
            return {
                projects: {},
                app_name: process.env.MIX_APP_NAME,
            }
        },
        mounted: function() {
            this.load();
        },
        components: {
            pagination
        },
        methods: {
            //shorting projects body
            readMore: function (text, length, suffix) {
                return text.substring(0, length) + suffix;
            },
            //getting all projects
            load: function(page = 1) {
                axios.get('/api/projects?page=' + page)
                .then(
                    response => {
                        this.projects =  (response.data.data);
                        //adding tooltip
                        Vue.nextTick(function () {
                            $('[data-toggle="tooltip"]').tooltip()
                        })
                    }     
                )
                .catch(function (error) {
                    this.errors.push(error);
                    console.log(error);
                })
            },
            //numbers decimals
            formatPrice(value) {
                let val = (value/1).toFixed(0).replace('.', ',')
                return val.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".")
            },
        }
    }
</script>
```

My pagination

```html
<pagination :data="projects" @pagination-change-page="load"></pagination>
```

and the error that I get is

```html
[Vue warn]: Invalid prop: type check failed for prop "data". Expected Object, got Array.
```

**Comment by gilbitron** [comment]
It looks like you're setting the `projects` value incorrectly:

```
this.projects = response.data;
```

See #18.

**Comment by robertnicjoo** [comment]
I've tried that before bust as i get my data with eager that won't pass my data to component.

Example:

```php
$projects = Project::with('user')->paginate(10)
```

I've also tried to put second data in my v-if like:

```html
v-if="project in projects.data"
```

Not work either.

**Comment by robertnicjoo** [comment]
@gilbitron  To make it more clear:


# option 1

```html
<div v-for="project in projects" :key="project.slug">
```

```javascript
load: function(page = 1) {
                axios.get('/api/projects?page=' + page)
                .then(
                    response => {
                        this.projects =  response.data.data;
                        //adding tooltip
                        Vue.nextTick(function () {
                            $('[data-toggle="tooltip"]').tooltip()
                        })
                    }     
                )
                .catch(function (error) {
                    this.errors.push(error);
                    console.log(error);
                })
 },
```

## result

![2018-08-14-09-59-12](https://user-images.githubusercontent.com/8672823/44069430-ecf1f404-9fa8-11e8-9e4e-bdb65a2a27db.jpg)

# option 2

If i use the same codes and just change my response to

```javascript
this.projects =  response.data;
```

## result

1.  No data in my view

2.
![2](https://user-images.githubusercontent.com/8672823/44069533-708bb3f4-9fa9-11e8-93c4-01d40e3c2aa0.png)
 

# option 3

You might say option 2 is the right one and I should add `.data` to my loop like:

```html
<div v-for="project in projects.data" :key="project.slug">
```

Well I've tried that as well and the `restult` is exact same as option 2 (No views and same debug results)

Please give some idea.

Thanks.

**Comment by toomtarm** [comment]
> @gilbitron To make it more clear:
> 
> # option 1
> ```
> <div v-for="project in projects" :key="project.slug">
> ```
> 
> ```js
> load: function(page = 1) {
>                 axios.get('/api/projects?page=' + page)
>                 .then(
>                     response => {
>                         this.projects =  response.data.data;
>                         //adding tooltip
>                         Vue.nextTick(function () {
>                             $('[data-toggle="tooltip"]').tooltip()
>                         })
>                     }     
>                 )
>                 .catch(function (error) {
>                     this.errors.push(error);
>                     console.log(error);
>                 })
>  },
> ```
> 
> ## result
> ![2018-08-14-09-59-12](https://user-images.githubusercontent.com/8672823/44069430-ecf1f404-9fa8-11e8-9e4e-bdb65a2a27db.jpg)
> 
> # option 2
> If i use the same codes and just change my response to
> 
> ```js
> this.projects =  response.data;
> ```
> 
> ## result
> 1. No data in my view
> 
> ![2](https://user-images.githubusercontent.com/8672823/44069533-708bb3f4-9fa9-11e8-93c4-01d40e3c2aa0.png)
> 
> # option 3
> You might say option 2 is the right one and I should add `.data` to my loop like:
> 
> ```
> <div v-for="project in projects.data" :key="project.slug">
> ```
> 
> Well I've tried that as well and the `restult` is exact same as option 2 (No views and same debug results)
> 
> Please give some idea.
> 
> Thanks.

Check your Controller 
You like be = "$user = DB::table('users')->all()" This Array
Actually = "$user = DB::table('users')->paginate(4)" This Object
