### ISSUE TITLE
{"isTrusted": true} instead of the page number in axios request

### ISSUE THREAD

**Issue by danhanly** [gilbitron/laravel-vue-pagination#27]
Our page number isn't being passed with the request, instead it's a json string: `{"isTrusted": true}` which is URL encoded.

Use of Component:
```
<Pagination :data="results" :limit="20" @pagination-change-page="loadData" v-if="results.data">
    <span slot="prev-nav">&laquo;</span>
    <span slot="next-nav">&raquo;</span>
</Pagination>
```
Load Data:
```
loadData (page) {
    axios.get(route('users'), {
          params: {
              term: this.search,
              page: page,
          },
     })
    .then(response => {
        this.results = response.data.results
    })
    .catch(e => {
         console.error({e})
    })
},
```

Here's the link that the axios request is generating upon searching:
/data/users?term=test&page=%7B%22isTrusted%22:true%7D

**Comment by gilbitron** [comment]
It looks like something external is appending the JSON strting `{"isTrusted": true}` to the generated URL. Could it be the `route('users')` method?

**Comment by danhanly** [comment]
I'm not ruling it out, but that method is part of the ziggy laravel routes package, which is in use across the entire ecosystem, it's only when we added pagination that we began to see this behaviour.

**Comment by danhanly** [comment]
Solved it.

Our `loadData` method is called in the initial search (activated by pressing `[Enter]`) and in the paginator. In one, it attaches the KeyboardEvent object (which shows up as `{"isTrusted": true}` when converted to a string), and in the other it shows up as a page number integer.

**Comment by danhanly** [comment]
Might go without saying, but @gilbitron I appreciate you taking time out to help with this issue. Thanks.
