### ISSUE TITLE
How to make a limit to the displayed number of pages?

### ISSUE THREAD

**Issue by CrocOne** [gilbitron/laravel-vue-pagination#31]
![uw4qz8g2](https://user-images.githubusercontent.com/43406446/46573463-59002e80-c99e-11e8-8fff-8356668529b8.png)
How to do in the form 1,2,3,4,5,6.....31 ?

**Comment by gilbitron** [comment]
Currently, you can't do this out of the box. You might be able to build your own component based on [RenderlessLaravelVuePagination.vue](https://github.com/gilbitron/laravel-vue-pagination/blob/master/src/RenderlessLaravelVuePagination.vue) though (see how we use this component in our own [LaravelVuePagination.vue](https://github.com/gilbitron/laravel-vue-pagination/blob/master/src/LaravelVuePagination.vue).

**Comment by CrocOne** [comment]
thanks
