### ISSUE TITLE
Pagination links not working.

### ISSUE THREAD

**Issue by pedroporto** [gilbitron/laravel-vue-pagination#36]
I'm using laravel paginate

`$data = DB::table('posts')->paginate(30);`

and passing to the laravel component as a json object.

`<pagination :data="data">
</pagination>`

The pagination displays correctly even when I change manually the $_GET['page'] parameter on the URL but the links are not displaying.

![screen shot 2018-12-16 at 13 25 01](https://user-images.githubusercontent.com/20285678/50054084-2610ae80-0136-11e9-8174-1f335ccd4a44.png)

**Comment by pedroporto** [comment]
> I'm not sure I follow. Is it displaying correctly or are the links not displaying?

The only thing not working are the links. The rest is fine

**Comment by pedroporto** [comment]
> Which links are you referring to? The links in the pagination? Do you mean the pagination links show but clicking on them does nothing?

The pagination component appears as the image above but the links displays with an empty href like this:
`<a href="#">`

**Comment by gilbitron** [comment]
Ok, I'm following you now.

That's correct the links contain a `#` as the `href`. You need to implement the `@pagination-change-page` event listener to actually change the page. From the docs:

```
<pagination :data="laravelData" @pagination-change-page="getResults"></pagination>

export default {
	//...

	methods: {
		// Our method to GET results from a Laravel endpoint
		getResults(page = 1) {
			axios.get('example/results?page=' + page)
				.then(response => {
					this.laravelData = response.data;
				});
		}
	}

}
```

**Comment by pedroporto** [comment]
@gilbitron it's working now. Thank you!
