### ISSUE TITLE
Use with filters

### ISSUE THREAD

**Issue by akmalhazim24** [gilbitron/laravel-vue-pagination#38]
Hi,

I have managed to set it up all clearly and it is working perfectly. But I got one problem. I'm trying to implement a filter function for my project and the Model (In Laravel) after filtering returns paginate() because of our standardize SOP. However, the initial results after filtering doesnt requires any query string but after filtering requires some filter string appended in the axios request. Do you have any suggestions in order to display the paginated results after filtering?
![image](https://user-images.githubusercontent.com/34267739/50546371-c0f2a800-0c61-11e9-928b-b407c62003cc.png)

Thank you

**Comment by gilbitron** [comment]
I think this may be outside of the scope of support of this package, but it sounds like you may need to pass the query string to the Vue component then combine it with the URL you use in axios.

**Comment by kerrsmith** [comment]
> 
> 
> > I think this may be outside of the scope of support of this package, but it sounds like you may need to pass the query string to the Vue component then combine it with the URL you use in axios.
> 
> Yup, exactly. I guess, I would make my own class at figure it around here.

I have just reached this point in my code - having the option to add a custom query string would be a great help for search or filtered lists.

**Comment by renalpha** [comment]
https://gist.github.com/renalpha/b82abbf55d6886daabe4d9c563d975af

Use with spatie laravel-query-builder
