### ISSUE TITLE
"TypeError: Cannot read property 'meta' of null"

### ISSUE THREAD

**Issue by blyleven** [gilbitron/laravel-vue-pagination#41]
Hi all, 

I've noticed the meta property is used within the component when using API resources. But when you're actually use a normal API route, which doesn't return a meta object but renders a normal pagination response, the meta attribute is not there. 

Is there some way I did not see yet, which could help me grab content via a normal API route?

As an example I've added this screenshot.

<img width="488" alt="data" src="https://user-images.githubusercontent.com/4598259/51943671-67c19400-241a-11e9-90a2-816afd17a45a.png">

**Comment by gilbitron** [comment]
Are you using `simplePaginate` pagination or the normal `paginate` method? This library does not currently support the `simplePaginate` method.

**Comment by blyleven** [comment]
@gilbitron goodmorning! I'm using the normal paginate method, like:

```
$videos = Movie::orderBy('id', 'desc')->paginate(12);
```

**Comment by blyleven** [comment]
I found out this meta property only returns when using api resources. In my case I wasn't using this. Is it wise to make this mandatory to use this package, or should it be optional?

**Comment by gilbitron** [comment]
This library does support pagination for normal responses as well as API resources. It's part of Laravel's design to not include a `meta` object in a normal pagination response.

**Comment by boyet007** [comment]
any solutions for laravel 8 as backend??
