### ISSUE TITLE
First and last page nav items

### ISSUE THREAD

**Issue by lucascnunes** [gilbitron/laravel-vue-pagination#45]
Could you add the span slots First and Last page?
Thanks for your work.

**Comment by gilbitron** [comment]
Can you explain the use case? Why would you need these?

**Comment by Mehroblatipov** [comment]
how to limit the column of buttons pagintation? in my project it go away from borders of scrin(there are 140 pages)??? how to add the limit?

**Comment by lucascnunes** [comment]
@gilbitron 
Use case:
`<pagination :data="data" @pagination-change-page="paginateData">`
`              <span slot="first-nav">Primeira</span>`
`              <span slot="prev-nav">&lt; Anterior</span>`
`              <span slot="next-nav">Próximo &gt;</span>`
`              <span slot="last-nav"> Última</span>`
`</pagination>`

"first-nav" would take you to the first page of the data
"last-nav" would take you to the last page of the data

Thanks for your attention.

**Comment by gilbitron** [comment]
@lucascnunes Ah ok I see what you mean 👍
