### ISSUE TITLE
Add option to modify component classes

### ISSUE THREAD

**Issue by clemquinones** [gilbitron/laravel-vue-pagination#46]
I'm working with a paid bootstrap 4 template and it has a special class(es) defined for pagination component to keep it blended to the template's theme. However, I can't seem to find a way to add these classes to the component.
This package is really great, but still need a bit of flexibility.

**Comment by gilbitron** [comment]
If you need this level of customization you can probably use the `RenderlessLaravelVuePagination` component and create your own markup with classes. See our [LaravelVuePagination](https://github.com/gilbitron/laravel-vue-pagination/blob/master/src/LaravelVuePagination.vue) component to see how we do this internally.

**Comment by stijnvanouplines** [comment]
How can we import the `RenderlessLaravelVuePagination` component and create our own markup?

**Comment by stijnvanouplines** [comment]
> How can we import the `RenderlessLaravelVuePagination` component and create our own markup?

Nevermind, I found it!

**Comment by clemquinones** [comment]
> > How can we import the `RenderlessLaravelVuePagination` component and create our own markup?
> 
> Nevermind, I found it!

care to share?

**Comment by clemquinones** [comment]
> If you need this level of customization you can probably use the `RenderlessLaravelVuePagination` component and create your own markup with classes. See our [LaravelVuePagination](https://github.com/gilbitron/laravel-vue-pagination/blob/master/src/LaravelVuePagination.vue) component to see how we do this internally.

alright, thanks. I'll look into that.
