### ISSUE TITLE
[Question] Browser history

### ISSUE THREAD

**Issue by rogervila** [gilbitron/laravel-vue-pagination#47]
Is there a built-in functionality to modify the browser history when a page is changed?
Then, if the user switches between pages, the browser back button can be used to display the previous page.

If it's not included, I think that it would be nice to add it as an enhancement. 

Thank you.

**Comment by gilbitron** [comment]
I think that feature would be outside the scope of this component. Something like that should really be implemented at the app level using some kind of router.
