### ISSUE TITLE
Pagination Limit Does not work

### ISSUE THREAD

**Issue by chhinsras** [gilbitron/laravel-vue-pagination#49]
<div class="card-footer"> 
                 <pagination :data="users" @pagination-change-page="getResults" align="left" limit="5">
                   <span slot="prev-nav">&lt; Previous</span>
	                <span slot="next-nav">Next &gt;</span>  
                 </pagination>
              </div>
            </div>

This is my code.

I would like to limit the number of showing paginated item. (It is about  5000 items)

**Comment by chhinsras** [comment]
<div class="card-footer"> 
                 <pagination :data="users" @pagination-change-page="getResults" align="left" limit="5">
                   <span slot="prev-nav">&lt; Previous</span>
	                <span slot="next-nav">Next &gt;</span>  
                 </pagination>
              </div>
            </div>

**Comment by chhinsras** [comment]
`<div class="card-footer"> 
                 <pagination :data="users" @pagination-change-page="getResults" align="left" limit="5">
                   <span slot="prev-nav">&lt; Previous</span>
	                <span slot="next-nav">Next &gt;</span>  
                 </pagination>
              </div>
            </div>`

**Comment by alucard18** [comment]
add this : before limit

**Comment by alucard18** [comment]
change limit="5" to :limit="5"

**Comment by chhinsras** [comment]
it works. thank
