### ISSUE TITLE
Pagination is not showing with Laravel 5.8

### ISSUE THREAD

**Issue by zooni7054** [gilbitron/laravel-vue-pagination#50]
I have implemented your package with vue 2.5.17 and laravel 5.8. Now error is showing in console and everything works fine. But pagination is not showing. I think it is not supporting laravel 5.8

![Pakwaan Admin](https://user-images.githubusercontent.com/14364018/56083851-ca380700-5e43-11e9-844d-2be45a4eddab.png)

![Capture](https://user-images.githubusercontent.com/14364018/56083866-fb183c00-5e43-11e9-9a55-845ee4008c14.PNG)

**Comment by gilbitron** [comment]
Can you share the code you are using to implement this in the component?

**Comment by zooni7054** [comment]
I have initialize the module in app.js
https://github.com/zooni7054/larastart/blob/master/resources/js/app.js

And used in the following component
https://github.com/zooni7054/larastart/blob/master/resources/js/components/UserComponent.vue

**Comment by gilbitron** [comment]
Thanks. The Vue code looks fine. Are you using ApiReponses or a normal paginator in the backend?

**Comment by zooni7054** [comment]
I am using normal default paginator of laravel.

**Comment by Mahdi-Ba** [comment]
I'm Using this maybe work for you 
npm install vue-resource @zooni7054

**Comment by jeffbarretocopam** [comment]
I also have the same issue , i did downgrade and not working
