### ISSUE TITLE
How to pass GET Params in the Url

### ISSUE THREAD

**Issue by blpraveen** [gilbitron/laravel-vue-pagination#51]
How to pass GET Params Search in the url to pagination For Example I have a page opened http://domain.com/?search=abc. How to change the paginate url to include search in the pagination link

**Comment by gilbitron** [comment]
I probably need to look into this, but off the top of my head, I don't think this is something that should be handled by this library.

**Comment by blpraveen** [comment]
Then how to pass the params in the url

**Comment by blpraveen** [comment]
I have edited the search it shows the category in the params. How to change the url in getResults.
       vuejs file
            getResults(page = 1) {
                        axios.get('api/post?page=' + page)
                            .then(response => {
                                this.posts = response.data;
                            });
                },

    php file

      public function searchByCategory(){
		
        if ($search = \Request::get('category')) {
            $posts = Post::where('category_id',$search)->orderBy('created_at','desc')->paginate(20);
			$querystringArray = Input::only(['category']);
			$posts->appends($querystringArray);
        }else{
            $posts = Post::latest()->paginate(10);
        }

        return $posts;

**Comment by schranzer235** [comment]
Hi folks!

This is easy, see code below


# List.Vue
```
<template>
    <div class="row">
        <div class="col">
            <div v-for="record in records.data" v-bind:key="record.id" class="mb-2">
                <record-item-component v-bind:record="record"></record-item-component>
            </div>

            <div class="text-center w-100" v-if="records.meta.last_page > 1">
                <pagination :limit="4" align="center" :data="records" @pagination-change-page="onPaginate" :show-disabled="true"></pagination>
            </div>
        </div>
    </div>
</template>

<script src="./List.js"></script>
```

# List.js
```
export default {
  'methods': {
    onPaginate(page) {
      this.$router.push({
        'name': 'your.named.route',
        'params': {page}
      });
    }
  },
  created() {
    this.loadRecords(this.$route.params.page || 1);
  },
  beforeRouteUpdate(to, from, next) {
    this.loadRecords(to.params.page);
    next();
  }
};
```

# route
```
import RecordsList from './../components/records/List.vue';
{
  'path': '/records/:page?',
  'name': 'records.list',
  'component': RecordsList
}
```
