### ISSUE TITLE
Doc: please document how to handle the per_page option

### ISSUE THREAD

**Issue by realtebo** [gilbitron/laravel-vue-pagination#52]
Hi ! Thanks for your excellent work.

I'd like to see an example in the documentation about how to handle the 'per_page' option.

**Comment by nemethit** [comment]
I don't understand the question. The `per_page`-option is handled via paginate by your Controller-Methode your've pointed the route at.

**Example (part in targeted controller)**:
```php
 public function getCustomerNote($id,$per_page) {
        return Customer\Note::find($id)->paginate($perPage);
    }
```

**Route Example**:
```php
Route::get('/customer/note/{id}/{per_page}', 'AppController@getCustomerNote');
```

Or do you try to archive something else?
