### ISSUE TITLE
Dots

### ISSUE THREAD

**Issue by AkhmedovSH** [gilbitron/laravel-vue-pagination#55]
This package not supports pagination with dots?
I think it will be better if package include this options becouse of so much data came from server

**Comment by gilbitron** [comment]
Can you share an example of what you mean? Normally you would only use dot pagination for image galleries, right?

**Comment by ManojKiranA** [comment]
i think he is talking about

![image](https://user-images.githubusercontent.com/30294553/61031628-8bcbcd00-a3dd-11e9-8081-652199d24c35.png)

@gilbitron @AkhmedovSH

**Comment by vahidalvandi** [comment]
oh yes , i have problem  with many pages

![Screenshot from 2019-07-22 22-47-03](https://user-images.githubusercontent.com/7871623/61654881-a69e1b80-acd2-11e9-927c-4dd5e4e1163b.png)

**Comment by vahidalvandi** [comment]
oh yes , i have problem with many pages
![Screenshot from 2019-07-22 22-47-03](https://user-images.githubusercontent.com/7871623/61655129-2926db00-acd3-11e9-8388-10a2856a89f9.png)

**Comment by vahidalvandi** [comment]
it solved this with limit

`    <pagination :limit="2" :data="catalogs" @pagination-change-page="getResult"></pagination>
`
