### ISSUE TITLE
Issue to show large number of pagination count, Please check screenshot

### ISSUE THREAD

**Issue by karamsingh90** [gilbitron/laravel-vue-pagination#56]
![image](https://user-images.githubusercontent.com/7549826/58785548-52948600-8603-11e9-8570-3643acf2daf3.png)

When pagination count became large then this library shows all the number, Which look bad. 
I think you got my point.

**Comment by gilbitron** [comment]
See the [`limit` option in the API](https://github.com/gilbitron/laravel-vue-pagination#api).

**Comment by karamsingh90** [comment]
@gilbitron Thank you so much, It's working.  It's my silly mistake doesn't check the options.
