### ISSUE TITLE
Pagination is not showing on single page

### ISSUE THREAD

**Issue by iamsajidjaved** [gilbitron/laravel-vue-pagination#59]
Hi, I'm using your package in a bigger SASS based project. I like it but I think there is one deficiency. 

**Deficiency:**
When I have one page then the pagination buttons are hidden and appear when the pages increase and become more than 1.

**My requirement is I want to show the pagination always. Even if there are only zero records in my Database.**

Thanks

**Comment by maliksajid** [comment]
Is there any solution to my problem?

**Comment by gilbitron** [comment]
What would you want to see when there is only 1 page of pagination?

**Comment by maliksajid** [comment]
I want to see something like this. but the next and previous button should
be disabled.
thanks for your response.
[image: Untitled.png]
