### ISSUE TITLE
have error with data passing

### ISSUE THREAD

**Issue by dexterns88** [gilbitron/laravel-vue-pagination#6]
After init pagination have error .
[Vue warn]: Invalid prop: type check failed for prop "data". Expected Object, got Array.

`
DB query:
DB::table('serviceBook')
          ->select('id', 'name')
          ->paginate(10);
`

This is json response:
`
{"
current_page":1,"
data":[{"id":7,"name":"sdadadad","brojSasijeVozila":"123456789","datumServisa":"2017-07-03"},{"id":8,"name":"Oov je jos jedan servis","brojSasijeVozila":"123456789","datumServisa":"2017-07-03"}],
"from":1,"last_page":2,"next_page_url":"http:\/\/lara.loc\/rest\/service\/get?page=2","path":"http:\/\/lara.loc\/rest\/service\/get","per_page":2,"prev_page_url":null,"to":2,"total":3}
`

**Comment by dexterns88** [comment]
"vue": {
      "version": "2.4.2",
 }

And laravel version 5.4

**Comment by dexterns88** [comment]
Sorry, error in my $http.post method in vue .

**Comment by m-alinasab** [comment]
hello @dexterns88 
You are improve this error ?

this error is on my project. :(
