### ISSUE TITLE
show all page index button

### ISSUE THREAD

**Issue by Mahdi-Ba** [gilbitron/laravel-vue-pagination#61]
Thank u for this component.
I have got 20 pages that show users in pagination component but show all number of pages index i want show briefly can you help me plz  [pagination](https://photos.app.goo.gl/WobJCd45rnFgqCK19)

**Comment by gilbitron** [comment]
See the [`limit` prop](https://github.com/gilbitron/laravel-vue-pagination#api)

**Comment by Mahdi-Ba** [comment]
Thank you.this component really nice
