### ISSUE TITLE
not working limit prop

### ISSUE THREAD

**Issue by salmantaghooni** [gilbitron/laravel-vue-pagination#67]
hi
not working limit props for me!!!
`<pagination
                        class="mb-0"
                        :data="laravelData"
                        @pagination-change-page="getResults"
                        :limit="2"
                         />`

**Comment by gilbitron** [comment]
In what way is it not working?

**Comment by salmantaghooni** [comment]
> In what way is it not working?
Not work limit prop for me

my code
`<pagination
                                class="mb-0"
                                :data="ticketspages"
                                @pagination-change-page="getTickets"
                                :limit="limit"
                                :show-disabled="showDisabled"
                                :size="size"
                                :align="align" />`

 `data() {
            return {
                status:-1,
                limit: 2,
                showDisabled: false,
                size: 'default',
                align: 'left',
                ticketspages:{},
            }
        }
`
getTickets(page = 1) {
                axios.get('/user/gettickets?page=' + page)
                    .then(res => {
                        this.ticketspages = res.data;
                    }).catch(err => {

                });
            }

**Comment by salmantaghooni** [comment]
> In what way is it not working?


![1](https://user-images.githubusercontent.com/47713527/68581020-d5f8b400-048c-11ea-8125-898e082323f7.jpg)

![2](https://user-images.githubusercontent.com/47713527/68581100-017b9e80-048d-11ea-958f-f1ac8f9a6704.jpg)


![3](https://user-images.githubusercontent.com/47713527/68581215-31c33d00-048d-11ea-884a-ecdeb2f87922.jpg)


![4](https://user-images.githubusercontent.com/47713527/68581353-81a20400-048d-11ea-9169-11900fde1109.jpg)
