### ISSUE TITLE
size and align not working

### ISSUE THREAD

**Issue by mihirpatel83** [gilbitron/laravel-vue-pagination#68]
`<pagination :data="allCalls" :limit="3" :show-disabled="true" :size="large" :align="center" v-on:pagination-change-page="getResults" ></pagination>`

Large & Align option are giving below warning however data, limit & show-disabled are working.

[Vue warn]: Property or method "large" is not defined on the instance
[Vue warn]: Property or method "align" is not defined on the instance

I am using Laravel 6, Vue 2.*.

**Comment by gilbitron** [comment]
As `size` and `align` are string options you need to remove the `:` prefix:

```
<pagination :data="allCalls" :limit="3" :show-disabled="true" size="large" align="center" v-on:pagination-change-page="getResults"></pagination>
```

**Comment by mihirpatel83** [comment]
> As `size` and `align` are string options you need to remove the `:` prefix:
> 
> ```
> <pagination :data="allCalls" :limit="3" :show-disabled="true" size="large" align="center" v-on:pagination-change-page="getResults"></pagination>
> ```

I will have to go through the basics again. Thank you.
