### ISSUE TITLE
Doesn't Work Laravel Vue Pagination

### ISSUE THREAD

**Issue by MohamedPHP** [gilbitron/laravel-vue-pagination#7]
// register the component
![image](https://user-images.githubusercontent.com/21959069/29900213-97dfebf8-8df0-11e7-8663-e2504311a2f0.png)

// laravel controller
![image](https://user-images.githubusercontent.com/21959069/29900218-a21c5dfe-8df0-11e7-800c-0f276fb905e5.png)

// component

`<pagination :data="users_table.usersPages" v-on:pagination-change-page="getAllUsers"></pagination>`

![image](https://user-images.githubusercontent.com/21959069/29900227-b49afa80-8df0-11e7-9df9-6861b5afb833.png)

**Comment by MohamedPHP** [comment]
Sorry I found the error.

**Comment by Sjoerrdd** [comment]
@MohamedPHP what was the error?
