### ISSUE TITLE
Cannot set :align="center"

### ISSUE THREAD

**Issue by maulik85** [gilbitron/laravel-vue-pagination#70]
```
<div class="card-footer">
   <div>
      <pagination :data="readings" :showDisabled="true" :align="center" :limit=2 @pagination-change-page="getResults"></pagination>
   </div>
</div>
```

Gives error 

> [Vue warn]: Property or method "center" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

**Comment by gilbitron** [comment]
You need to remove the colon `:` as the value is a string (e.g. `align="center"`).

**Comment by ultrono** [comment]
Assuming this was an old prop. Without using the renderless component you can simply wrap your chosen style as follows:

````html
<div class="flex justify-center">
   <TailwindPagination ... />
</div>
````
