### ISSUE TITLE
How to send request on click  page number button.

### ISSUE THREAD

**Issue by ammadmaddydev** [gilbitron/laravel-vue-pagination#71]
![image](https://user-images.githubusercontent.com/26835424/77174911-9a799080-6ae3-11ea-95c2-a44d05cac0e3.png)

Can any one tell me that how to send request with "Page Number" on click on any page from pagination.

![image](https://user-images.githubusercontent.com/26835424/77175236-18d63280-6ae4-11ea-8793-2cc6249158c7.png)

![image](https://user-images.githubusercontent.com/26835424/77175192-03610880-6ae4-11ea-9a56-328d3771c15e.png)

**Comment by dieume-n** [comment]
```html
<paginate :data="paginated :limit="10" @pagination-change-page="get_posts"></pagination>
```
```js
<script>
...
methods: {
get_posts(page){
 // the value of page is passed automatically when changing the page number
  axios.get(`get_all_projects?pahe=${page})
          .then(response => { 
              // get your data
           }
}

</script>
```
