### ISSUE TITLE
How to install it without npm?

### ISSUE THREAD

**Issue by zarpio** [gilbitron/laravel-vue-pagination#74]
Can we use it on a simple Laravel website? I have an old website without VueJs but only 1 page which is using VueJs and I want to use this package directly on it... please suggest how to implement it.

I am using direct VueJs and other libs as follows.

```
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
```

**Comment by gilbitron** [comment]
You can use the [Unpkg CDN](https://unpkg.com/) to load the file without using NPM:

```
<script src="https://unpkg.com/laravel-vue-pagination@2.3.1/dist/laravel-vue-pagination.umd.min.js"></script>
```

**Comment by zarpio** [comment]
Thanks for the guide, but after placing it, getting this error.
`Uncaught ReferenceError: pagination is not defined`

**Comment by gilbitron** [comment]
You'll still need to register the component in Vue:

```
Vue.component('pagination', require('laravel-vue-pagination'));
```

**Comment by zarpio** [comment]
Give me following error :-(
`Uncaught ReferenceError: require is not defined`

Please check I have placed full code on StackOverflow [https://stackoverflow.com/questions/61792218/vusjs-component-using-cdn-link-without-npm](url)

**Comment by zarpio** [comment]
@gilbitron both links are fantastic for resolving my problem... 

1. [https://stackoverflow.com/questions/61792218/vuejs-component-using-cdn-link-without-npm/61793356#61793356](url)
3. [https://stackoverflow.com/questions/50052853/using-components-without-npm-inside-existing-web-page/50054132?noredirect=1#comment109318793_50054132](url)

Please update your README file if anyone wants to use your component without npm.
