### ISSUE TITLE
browser module

### ISSUE THREAD

**Issue by brendaniel** [gilbitron/laravel-vue-pagination#8]
**Can you upgrade it to use in the browser?**

**Comment by muhghazaliakbar** [comment]
what do you mean?

**Comment by brendaniel** [comment]
@muhghazaliakbar 

like vee-validate
https://github.com/baianat/vee-validate/blob/master/dist/vee-validate.js#L9

![image](https://user-images.githubusercontent.com/11773683/32210108-3acf9bfe-be4f-11e7-8977-8e7d75d6ba1f.png)


I want to use it in es5 as the code below
``` html
<script src="path/to/vue-pagination.js">
<script>
Vue.use(VuePagination);
...
</script>
<body>
<pagination :data="laravelData" v-on:pagination-change-page="getResults"></pagination>
</body>
```
