### ISSUE TITLE
Limit the number of page tabs to be displayed

### ISSUE THREAD

**Issue by austinkregel** [gilbitron/laravel-vue-pagination#9]
If you can, limit the number of pages to the first 7 or 8 pages, have an ellipse, then show the last two pages.

It get's really obnoxious to paginate 50,000+ results... The page count is.... too many...
![screenshot 2017-11-19 at 12 25 05 am](https://user-images.githubusercontent.com/5355937/32987659-1e0d9e2e-ccc0-11e7-98d9-865687f5b4da.png)

**Comment by scotthughestech** [comment]
Hi Austin,

I'm not the author, but I just figured this out, so I thought I would share. Add this "limit" prop when using the component:

<pagination :data="laravelData" :limit="3" v-on:pagination-change-page="getResults"></pagination>

It doesn't work exactly the same as the Laravel paginator, but it'll work better than what's in your screenshot.

**Comment by austinkregel** [comment]
Hey Scott,
I guess I should have read the docs more thoroughly. 🙃  Thanks a bunch!
