### ISSUE TITLE
Paginate error

### ISSUE THREAD

**Issue by Ryunosukee** [gilbitron/laravel-vue-pagination#92]
When I load the table the pagination doesn't work, is there any way to fix it? or am I using it in the wrong way?

![Captura de pantalla 2020-11-10 a la(s) 8 57 04 a  m](https://user-images.githubusercontent.com/54317215/98683190-be1f6e80-2332-11eb-9363-beba06b40da2.png)

![Captura de pantalla 2020-11-10 a la(s) 8 58 11 a  m](https://user-images.githubusercontent.com/54317215/98683339-e9a25900-2332-11eb-8f5f-3b2e81129b90.png)

Thanks for the help.

**Comment by gilbitron** [comment]
How are you passing data to the pagination component?

**Comment by pianistprogrammer** [comment]
I reverted to an old version 1.0.6 that once worked in another project... but it doesn't even render in my new proj
