### ISSUE TITLE
Vue 3.x support working

### ISSUE THREAD

**Issue by barryp** [gilbitron/laravel-vue-pagination#95]
Just an FYI - I took a stab at migrating to Vue 3.x, it really wasn't too bad - most of the work was really just updating the unit tests to use the newer @vue/test-utils

It's in a [vue3 branch](/barryp/laravel-vue-pagination/tree/vue3) of my fork

**Comment by gilbitron** [comment]
Thanks @barryp. Feel free to submit a PR from your branch.

**Comment by barryp** [comment]
Great, here it is #97
