### ISSUE TITLE
Current Page - Support

### ISSUE THREAD

**Issue by guillmz** [gilbitron/laravel-vue-pagination#98]
Hi everyone ;
How can I get the current page value to use it when I refresh the table and move directly to that page and not to the page 1 ?

Regards
and Thanks !

**Comment by darkness0710** [comment]
> Hi everyone ;
> How can I get the current page value to use it when I refresh the table and move directly to that page and not to the page 1 ?
> 
> Regards
> and Thanks !

You can get from data (In example this.laravelData.current_page)

**Comment by selmiAmine** [comment]
> > Hi everyone ;
> > How can I get the current page value to use it when I refresh the table and move directly to that page and not to the page 1 ?
> > Regards
> > and Thanks !
> 
> You can get from data (In example this.laravelData.current_page)

Can you explain more ?

**Comment by darkness0710** [comment]
> > > Hi everyone ;
> > > How can I get the current page value to use it when I refresh the table and move directly to that page and not to the page 1 ?
> > > Regards
> > > and Thanks !
> > 
> > 
> > You can get from data (In example this.laravelData.current_page)
> 
> Can you explain more ?
> Becuase im facing the same issue.
U can see my example:
https://github.com/darkness0710/vuex-laravel/blob/master/resources/js/components/customers/List.vue
